#!/bin/sh

CJSDELIVERY_VER="0.4.2"
CJSDELIVERY_TMP="/tmp/cjsdelivery"
CJSDELIVERY_URL="https://github.com/mattcg/cjsdelivery/archive/v$CJSDELIVERY_VER.zip"

# Stop on first error
set -e

echo "Creating temporary dir:"
echo "\t$CJSDELIVERY_TMP"

mkdir -p "$CJSDELIVERY_TMP"

echo "Downloading:"
echo "\t$CJSDELIVERY_URL"

CJSDELIVERY_ZIP="$CJSDELIVERY_TMP/v$CJSDELIVERY_VER.zip"
CJSDELIVERY_DIR="$CJSDELIVERY_TMP/cjsdelivery-$CJSDELIVERY_VER"

curl "$CJSDELIVERY_URL" -o "$CJSDELIVERY_ZIP" --progress-bar --location
unzip -q "$CJSDELIVERY_ZIP" -d "$CJSDELIVERY_TMP/"

pushd "$CJSDELIVERY_DIR" > /dev/null 2>&1
"$CJSDELIVERY_DIR/scripts/install.sh"
popd > /dev/null 2>&1

echo "Removing:"
echo "\t$CJSDELIVERY_TMP"

rm -rf "$CJSDELIVERY_TMP"

echo "Done."
